### ISSUE TITLE
janus-proxy run error 

### ISSUE THREAD

**Issue by ktj4820** [OpenSight/janus-cloud#24]
When janus-proxy is run, the error "socket operation on non-socket" appears.

sudo janus-proxy
--------------------------------------------------------------------------------
Janus-proxy loads the config file: /opt/janus-cloud/conf/janus-proxy.yml
Traceback (most recent call last):
  File "/usr/local/bin/janus-proxy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/januscloud/proxy/main.py", line 16, in main
    with DaemonContext(stdin=sys.stdin,
  File "/usr/local/lib/python3.8/dist-packages/daemon/daemon.py", line 273, in __init__
    detach_process = is_detach_process_context_required()
  File "/usr/local/lib/python3.8/dist-packages/daemon/daemon.py", line 821, in is_detach_process_context_required
    if is_process_started_by_init() or is_process_started_by_superserver():
  File "/usr/local/lib/python3.8/dist-packages/daemon/daemon.py", line 798, in is_process_started_by_superserver
    if is_socket(stdin_fd):
  File "/usr/local/lib/python3.8/dist-packages/daemon/daemon.py", line 764, in is_socket
    file_socket = socket.fromfd(fd, socket.AF_INET, socket.SOCK_RAW)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_socket3.py", line 715, in fromfd
    return socket(family, type, proto, nfd)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_socket3.py", line 142, in __init__
    self._sock = self._gevent_sock_class(family, type, proto, fileno)
OSError: [Errno 88] Socket operation on non-socket

**Comment by ktj4820** [comment]
We've solved it. Thank you.

**Comment by jamken** [comment]
I never run janus-proxy in phton 3.8, maybe some dependants is not compatible which need to upgrade to a new version. Thanks

**Comment by jamken** [comment]
I have run janus-proxy in python 3.8，and it start up without error.

**Comment by hryjosn** [comment]
Hi @ktj4820, I have the same issue, how do you solve it?
